services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: raita-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/raitabandhu
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: raita-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
